# Makefile for my lithium ion 21700 adapter

lithium.stl:	lithium.scad
	openscad -o lithium.stl lithium.scad

SD = /run/media/tom/6331-3331/

copy:
	#cp lithium.gcode $(SD)
	cp CE3PRO_lithium.gcode $(SD)/lithium.gcode
